# escape=`
FROM mcr.microsoft.com/windows/servercore:ltsc2022

RUN @"%SystemRoot%\System32\WindowsPowerShell\v1.0\powershell.exe" -NoProfile -InputFormat None -ExecutionPolicy Bypass -Command " [System.Net.ServicePointManager]::SecurityProtocol = 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))" && SET "PATH=%PATH%;%ALLUSERSPROFILE%\chocolatey\bin"
RUN choco install git.install -y
RUN choco install cmake -y --installargs '"ADD_CMAKE_TO_PATH=System"'
RUN choco install visualstudio2017-workload-vctools -y
RUN git clone https://github.com/microsoft/vcpkg.git C:\vcpkg `
    && cd vcpkg `
    && bootstrap-vcpkg.bat `
    && SETX /M PATH "C:\vcpkg;%PATH%" `
    && vcpkg install zlib:x64-windows --clean-after-build `
    && vcpkg remove zlib:x64-windows
RUN choco install python -y

ENTRYPOINT ["C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildTools\\VC\\Auxiliary\\Build\\vcvars64.bat", "&&", "powershell.exe", "-NoLogo", "-ExecutionPolicy", "Bypass"]