name: CentOS 7 Builder
on:
  push: 
    branches:
      - main
    paths:
      - .github/workflows/centos7-builder.yml
  schedule:
    - cron: "0 5 1 * *" # 5:00 on the first day of each month
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Write Dockerfile
      run: |
        cat <<EOF > Dockerfile
        FROM centos:7
        RUN yum install -y epel-release
        RUN yum install -y python3 python3-pip git wget
        RUN pip3 install --upgrade pip
        RUN pip3 install numpy protobuf wheel ninja
        COPY . /paddle
        WORKDIR /paddle
        CMD ["/bin/bash"]
        EOF

    - name: Show Dockerfile
      run: cat Dockerfile

    - name: Build Docker image
      run: |
        docker build -t centos7-builder .