name: CentOS 7 Builder
on:
  push: 
    branches:
      - main
    paths:
      - .github/workflows/centos7-builder.yml
  schedule:
    - cron: "0 5 1 * *" # 5:00 on the first day of each month
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Write Dockerfile
      run: |
        cat <<EOF > Dockerfile
        FROM oraclelinux:7
        RUN yum install -y oracle-epel-release-el7 && yum-config-manager --enable ol7_developer_epel
        RUN yum install -y gcc cmake3 gcc-c++ make nasm && ln -s /usr/bin/cmake3 /usr/bin/cmake
        EOF

    - name: Show Dockerfile
      run: cat Dockerfile

    - name: Build Docker image
      run: |
        docker build -t centos7-builder .

    - name: Test Docker image
      run: |
        docker run --rm centos7-builder sh -c "gcc --version && cmake --version && make --version && nasm --version"