name: cuda
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/cuda.yml
  workflow_dispatch:

jobs:
  build-all:
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-2022]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: Jimver/cuda-toolkit@master
      id: cuda-toolkit
      with:
        method: network
        # Windows sub-packages are kind of different, so we need to handle them separately
        # https://docs.nvidia.com/cuda/cuda-installation-guide-microsoft-windows/index.html
        sub-packages: ${{ matrix.os == 'ubuntu-22.04' && '["nvcc"]' || '["nvcc", "cublas", "cublas-dev"]' }}
        non-cuda-sub-packages: ${{ matrix.os == 'ubuntu-22.04' && '["libcublas", "libcublas-dev"]' || '' }}
        log-file-suffix: '${{matrix.os}}.txt'

    - name: Show CUDA
      run: |
        echo "Cuda install location: ${{steps.cuda-toolkit.outputs.CUDA_PATH}}"
        echo "Installed cuda version is: ${{steps.cuda-toolkit.outputs.cuda}}"
        nvcc --version

    - name: Show CUDA Artifacts
      shell: bash
      run: |
        echo "CUDA artifacts:"
        ls -lR "${{steps.cuda-toolkit.outputs.CUDA_PATH}}"