name: cuda
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/cuda.yml
  workflow_dispatch:

jobs:
  build-all:
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-2022]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: Jimver/cuda-toolkit@master
      id: cuda-toolkit
      with:
        method: network
        sub-packages: '["nvcc"]'
        non-cuda-sub-packages: '["libcublas", "libcublas-dev"]'
        log-file-suffix: '${{matrix.os}}.txt'

    - name: Show CUDA
      run: |
        echo "Cuda install location: ${{steps.cuda-toolkit.outputs.CUDA_PATH}}"
        echo "Installed cuda version is: ${{steps.cuda-toolkit.outputs.cuda}}"
        nvcc --version

    - name: Show CUDA Artifacts
      shell: bash
      run: |
        echo "CUDA artifacts:"
        ls -lR "${{steps.cuda-toolkit.outputs.CUDA_PATH}}"