name: msvc
on:
  schedule:
    - cron: "0 16 * * 0"
  workflow_dispatch:

jobs:
  msvc2017:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker registries
        run: |
          . .\scripts\docker-utils.ps1
          Login-DockerRegistries -aliyunUsername -dockerUsername "${{ env.DOCKER_USERNAME }}" -dockerToken "${{ secrets.DOCKER_PASSWORD }}" -githubOwner "${{ github.repository_owner }}" -githubToken "${{ secrets.GITHUB_TOKEN }}"
        shell: pwsh

      - name: Build
        run: |
          cd ./src/msvc/msvc2017
          docker build -t msvc2017 .
      
      - name: Tag and Push Docker images
        run: |
          . .\scripts\docker-utils.ps1
          TagAndPushDockerImages -imageName "msvc2017" -githubRepository "${{ github.repository }}" -dockerUsername "${{ env.DOCKER_USERNAME }}" -runId ${{ github.run_number }}
        shell: pwsh

  msvc2019:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker registries
        run: |
          . .\scripts\docker-utils.ps1
          Login-DockerRegistries -aliyunUsername -dockerUsername "${{ env.DOCKER_USERNAME }}" -dockerToken "${{ secrets.DOCKER_PASSWORD }}" -githubOwner "${{ github.repository_owner }}" -githubToken "${{ secrets.GITHUB_TOKEN }}"
        shell: pwsh

      - name: Build
        run: |
          cd ./src/msvc/msvc2019
          docker build -t msvc2019 .
      
      - name: Tag and Push Docker images
        run: |
          . .\scripts\docker-utils.ps1
          TagAndPushDockerImages -imageName "msvc2019" -githubRepository "${{ github.repository }}" -dockerUsername "${{ env.DOCKER_USERNAME }}" -runId ${{ github.run_number }}
        shell: pwsh

  msvc2022:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker registries
        run: |
          . .\scripts\docker-utils.ps1
          Login-DockerRegistries -aliyunUsername -dockerUsername "${{ env.DOCKER_USERNAME }}" -dockerToken "${{ secrets.DOCKER_PASSWORD }}" -githubOwner "${{ github.repository_owner }}" -githubToken "${{ secrets.GITHUB_TOKEN }}"
        shell: pwsh

      - name: Build
        run: |
          cd ./src/msvc/msvc2022
          docker build -t msvc2022 .
      
      - name: Tag and Push Docker images
        run: |
          . .\scripts\docker-utils.ps1
          TagAndPushDockerImages -imageName "msvc2022" -githubRepository "${{ github.repository }}" -dockerUsername "${{ env.DOCKER_USERNAME }}" -runId ${{ github.run_number }}
        shell: pwsh