name: paddle-windows-build
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/paddle-windows-build.yml'
  workflow_dispatch:

env:
  PADDLE_VERSION: "2.6.1"
  PADDLE_BRANCH: "release/2.6"

jobs:
  build-all:
    runs-on: windows-2022
    strategy:
      matrix:
        build_config:
          - name: openblas_noavx
            AVX_FLAG: OFF
            MKL_FLAG: OFF
          - name: openblas
            AVX_FLAG: ON
            MKL_FLAG: OFF
          - name: mkldnn
            AVX_FLAG: ON
            MKL_FLAG: ON
    steps:
      - name: Create Dev Drive using ReFS
        run: |
          $Volume = New-VHD -Path C:/dev-drive.vhdx -SizeBytes 40GB |
                    Mount-VHD -Passthru |
                    Initialize-Disk -Passthru |
                    New-Partition -AssignDriveLetter -UseMaximumSize |
                    Format-Volume -FileSystem NTFS -Confirm:$false -Force
          Write-Output $Volume
          Write-Output "DEV_DRIVE=$($Volume.DriveLetter):" >> $env:GITHUB_ENV

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Setup dependencies
        run: |
          pip3 install numpy protobuf wheel ninja

      - uses: ilammy/msvc-dev-cmd@v1

      - name: Clone Paddle repository
        run: |
          Write-Host "Executing: git clone $env:PADDLE_BRANCH from: https://github.com/PaddlePaddle/Paddle"
          git clone --depth 1 -b $env:PADDLE_BRANCH https://github.com/PaddlePaddle/Paddle ${{ env.DEV_DRIVE }}\Paddle

      - name: Configure with CMake
        run: |
          mkdir ${{ env.DEV_DRIVE }}\Paddle\Build
          cd ${{ env.DEV_DRIVE }}\Paddle\Build
          cmake .. -GNinja `
            -DWITH_AVX=${{ matrix.build_config.AVX_FLAG }} `
            -DWITH_MKL=${{ matrix.build_config.MKL_FLAG }} `
            -DWITH_GPU=OFF `
            -DON_INFER=ON `
            -DWITH_PYTHON=OFF `
            -DWITH_ONNXRUNTIME=ON `
            -DWITH_UNITY_BUILD=ON

      - name: Build with Ninja
        run: |
          cd ${{ env.DEV_DRIVE }}\Paddle\Build
          ninja all

      - name: Copy common* files
        run: |
          cp ${{ env.DEV_DRIVE }}\Paddle\Build\paddle_inference_install_dir\paddle\lib\common* ${{ env.DEV_DRIVE }}\Paddle\Build\paddle_inference_c_install_dir\paddle\lib
          ls ${{ env.DEV_DRIVE }}\Paddle\Build

      - name: Upload paddle_inference_c_install_dir
        uses: actions/upload-artifact@v4
        with:
          name: c_${{ matrix.build_config.name }}
          path: ${{ env.DEV_DRIVE }}\Paddle\Build\paddle_inference_c_install_dir\*

      - name: Upload paddle_inference_install_dir
        uses: actions/upload-artifact@v4
        with:
          name: cpp_${{ matrix.build_config.name }}
          path: ${{ env.DEV_DRIVE }}\Paddle\Build\paddle_inference_install_dir\*
    
  # cu120-sm86-89:
  #   runs-on: windows-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4

  #     - name: Build
  #       run: |
  #         cd ./.github/workflows/paddle-windows-build
  #         docker run -e PADDLE_VERSION=2.6.1 -e PADDLE_BRANCH=release/2.6 -v ${PWD}\paddle-windows-build:C:\scripts --name build sdflysha/msvc2019-cu120:latest C:\scripts\cu120-sm86-89.ps1
      
  #     - name: copy artifacts
  #       run: |
  #         docker create --name build build
  #         docker cp build:${{ env.DEV_DRIVE }}\Paddle\Build\build.zip .
  #         docker rm build
    
  # cu120-sm61-75:
  #   runs-on: windows-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4

  #     - name: Build
  #       run: |
  #         cd ./.github/workflows/paddle-windows-build
  #         docker run -e PADDLE_VERSION=2.6.1 -e PADDLE_BRANCH=release/2.6 -v ${PWD}\paddle-windows-build:C:\scripts --name build sdflysha/msvc2019-cu120:latest C:\scripts\cu120-sm86-89.ps1
      
  #     - name: copy artifacts
  #       run: |
  #         docker create --name build build
  #         docker cp build:${{ env.DEV_DRIVE }}\Paddle\Build\build.zip .
  #         docker rm build
    
  # cu120-sm80:
  #   runs-on: windows-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4

  #     - name: Build
  #       run: |
  #         cd ./.github/workflows/paddle-windows-build
  #         docker run -e PADDLE_VERSION=2.6.1 -e PADDLE_BRANCH=release/2.6 -v ${PWD}\paddle-windows-build:C:\scripts --name build sdflysha/msvc2019-cu120:latest C:\scripts\cu120-sm80.ps1
      
  #     - name: copy artifacts
  #       run: |
  #         docker create --name build build
  #         docker cp build:${{ env.DEV_DRIVE }}\Paddle\Build\build.zip .
  #         docker rm build
    