name: paddle-windows-build
on:
  workflow_dispatch:
    inputs:
      paddle_version:
        description: 'Paddle version'
        required: true
        default: '2.6.1'

jobs:
  openblas-noavx:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: |
          cd ./.github/workflows/paddle-windows-build
          docker run -it -e PADDLE_VERSION=2.6.1 -e PADDLE_BRANCH=release/2.6 -v ${PWD}\paddle-windows-build:C:\scripts --name build sdflysha/msvc2019:latest C:\scripts\openblas-noavx.ps1
      
      - name: copy artifacts
        run: |
          docker create --name build build
          docker cp build:C:\Paddle\Build\build.zip .
          docker rm build
    
  openblas:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: |
          cd ./.github/workflows/paddle-windows-build
          docker run -it -e PADDLE_VERSION=2.6.1 -e PADDLE_BRANCH=release/2.6 -v ${PWD}\paddle-windows-build:C:\scripts --name build sdflysha/msvc2019:latest C:\scripts\openblas.ps1
      
      - name: copy artifacts
        run: |
          docker create --name build build
          docker cp build:C:\Paddle\Build\build.zip .
          docker rm build
    
  mkldnn:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: |
          cd ./.github/workflows/paddle-windows-build
          docker run -it -e PADDLE_VERSION=2.6.1 -e PADDLE_BRANCH=release/2.6 -v ${PWD}\paddle-windows-build:C:\scripts --name build sdflysha/msvc2019:latest C:\scripts\mkldnn.ps1
      
      - name: copy artifacts
        run: |
          docker create --name build build
          docker cp build:C:\Paddle\Build\build.zip .
          docker rm build
    
  cu120-sm86-89:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: |
          cd ./.github/workflows/paddle-windows-build
          docker run -it -e PADDLE_VERSION=2.6.1 -e PADDLE_BRANCH=release/2.6 -v ${PWD}\paddle-windows-build:C:\scripts --name build sdflysha/msvc2019-cu120:latest C:\scripts\cu120-sm86-89.ps1
      
      - name: copy artifacts
        run: |
          docker create --name build build
          docker cp build:C:\Paddle\Build\build.zip .
          docker rm build
    
  cu120-sm61-75:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: |
          cd ./.github/workflows/paddle-windows-build
          docker run -it -e PADDLE_VERSION=2.6.1 -e PADDLE_BRANCH=release/2.6 -v ${PWD}\paddle-windows-build:C:\scripts --name build sdflysha/msvc2019-cu120:latest C:\scripts\cu120-sm86-89.ps1
      
      - name: copy artifacts
        run: |
          docker create --name build build
          docker cp build:C:\Paddle\Build\build.zip .
          docker rm build
    