name: paddle-windows-build
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/paddle-windows-build.yml'
  workflow_dispatch:

jobs:
  openblas-noavx:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: setup deps
        run: |
          pip3 install numpy protobuf wheel ninja

      - name: run
        run: |
          $env:PADDLE_VERSION = "2.6.1"
          $env:PADDLE_BRANCH = "release/2.6"
          Write-Host "Executing: git clone $env:PADDLE_BRANCH from: https://github.com/PaddlePaddle/Paddle"
          git clone --depth 1 -b $env:PADDLE_BRANCH https://github.com/PaddlePaddle/Paddle C:\Paddle
          mkdir C:\Paddle\Build
          cd C:\Paddle\Build

          cmake .. -GNinja -DWITH_AVX=OFF -DWITH_MKL=OFF -DWITH_GPU=OFF -DON_INFER=ON -DWITH_PYTHON=OFF -DWITH_ONNXRUNTIME=ON -DWITH_UNITY_BUILD=ON
          ninja all

          cp C:\Paddle\Build\paddle_inference_install_dir\paddle\lib\common* C:\Paddle\Build\paddle_inference_c_install_dir\paddle\lib
          Compress-Archive -Path C:\Paddle\Build\paddle_inference_c_install_dir\* -DestinationPath C:\Paddle\Build\c.zip
          Compress-Archive -Path C:\Paddle\Build\paddle_inference_install_dir\* -DestinationPath C:\Paddle\Build\cpp.zip
          ls C:\Paddle\Build
      
      - name: Upload paddle_inference_c_install_dir artifacts
        uses: actions/upload-artifact@v4
        with:
          name: paddle_inference_c_install_dir
          path: C:\Paddle\Build\paddle_inference_c_install_dir\*
  
      - name: Upload paddle_inference_install_dir artifacts
        uses: actions/upload-artifact@v4
        with:
          name: paddle_inference_install_dir
          path: C:\Paddle\Build\paddle_inference_install_dir\*
    
  # openblas:
  #   runs-on: windows-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4

  #     - name: Build
  #       run: |
  #         cd ./.github/workflows/paddle-windows-build
  #         docker run -e PADDLE_VERSION=2.6.1 -e PADDLE_BRANCH=release/2.6 -v ${PWD}\paddle-windows-build:C:\scripts --name build sdflysha/msvc2019:latest C:\scripts\openblas.ps1
      
  #     - name: copy artifacts
  #       run: |
  #         docker create --name build build
  #         docker cp build:C:\Paddle\Build\build.zip .
  #         docker rm build
    
  # mkldnn:
  #   runs-on: windows-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4

  #     - name: Build
  #       run: |
  #         cd ./.github/workflows/paddle-windows-build
  #         docker run -e PADDLE_VERSION=2.6.1 -e PADDLE_BRANCH=release/2.6 -v ${PWD}\paddle-windows-build:C:\scripts --name build sdflysha/msvc2019:latest C:\scripts\mkldnn.ps1
      
  #     - name: copy artifacts
  #       run: |
  #         docker create --name build build
  #         docker cp build:C:\Paddle\Build\build.zip .
  #         docker rm build
    
  # cu120-sm86-89:
  #   runs-on: windows-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4

  #     - name: Build
  #       run: |
  #         cd ./.github/workflows/paddle-windows-build
  #         docker run -e PADDLE_VERSION=2.6.1 -e PADDLE_BRANCH=release/2.6 -v ${PWD}\paddle-windows-build:C:\scripts --name build sdflysha/msvc2019-cu120:latest C:\scripts\cu120-sm86-89.ps1
      
  #     - name: copy artifacts
  #       run: |
  #         docker create --name build build
  #         docker cp build:C:\Paddle\Build\build.zip .
  #         docker rm build
    
  # cu120-sm61-75:
  #   runs-on: windows-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4

  #     - name: Build
  #       run: |
  #         cd ./.github/workflows/paddle-windows-build
  #         docker run -e PADDLE_VERSION=2.6.1 -e PADDLE_BRANCH=release/2.6 -v ${PWD}\paddle-windows-build:C:\scripts --name build sdflysha/msvc2019-cu120:latest C:\scripts\cu120-sm86-89.ps1
      
  #     - name: copy artifacts
  #       run: |
  #         docker create --name build build
  #         docker cp build:C:\Paddle\Build\build.zip .
  #         docker rm build
    
  # cu120-sm80:
  #   runs-on: windows-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4

  #     - name: Build
  #       run: |
  #         cd ./.github/workflows/paddle-windows-build
  #         docker run -e PADDLE_VERSION=2.6.1 -e PADDLE_BRANCH=release/2.6 -v ${PWD}\paddle-windows-build:C:\scripts --name build sdflysha/msvc2019-cu120:latest C:\scripts\cu120-sm80.ps1
      
  #     - name: copy artifacts
  #       run: |
  #         docker create --name build build
  #         docker cp build:C:\Paddle\Build\build.zip .
  #         docker rm build
    