name: paddle-linux-build
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/paddle-linux-build.yml'
  workflow_dispatch:

env:
  PADDLE_VERSION: "2.6.1"
  PADDLE_BRANCH: "release/2.6"

jobs:
  build-all:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        build_config:
          - name: openblas_noavx
            AVX_FLAG: OFF
            MKL_FLAG: OFF
          - name: openblas
            AVX_FLAG: ON
            MKL_FLAG: OFF
          - name: mkldnn
            AVX_FLAG: ON
            MKL_FLAG: ON
    steps:
      - name: Setup dependencies
        run: |
          pip3 install numpy protobuf wheel ninja

      - name: Clone Paddle repository
        run: |
          echo "Executing: git clone $PADDLE_BRANCH from: https://github.com/PaddlePaddle/Paddle"
          git clone --depth 1 -b $PADDLE_BRANCH https://github.com/PaddlePaddle/Paddle ~/Paddle

      - name: Configure with CMake
        run: |
          mkdir -p ~/Paddle/Build
          cd ~/Paddle/Build
          cmake .. -GNinja \
            -DWITH_AVX=${{ matrix.build_config.AVX_FLAG }} \
            -DWITH_MKL=${{ matrix.build_config.MKL_FLAG }} \
            -DWITH_GPU=OFF \
            -DON_INFER=ON \
            -DWITH_PYTHON=OFF \
            -DWITH_ONNXRUNTIME=ON \
            -DWITH_UNITY_BUILD=ON

      - name: Build with Ninja
        run: |
          cd ~/Paddle/Build
          ninja all

      - name: Copy so files
        run: |
          ls ~/Paddle/paddle/fluid/inference/capi_exp/
          cp ~/Paddle/paddle/fluid/inference/capi_exp/* ~/Paddle/Build/paddle_inference_c_install_dir/

          ls ~/Paddle/paddle/fluid/inference/
          cp ~/Paddle/paddle/fluid/inference/* ~/Paddle/Build/paddle_inference_install_dir/

      - name: Upload paddle_inference_c_install_dir
        uses: actions/upload-artifact@v4
        with:
          name: c_${{ matrix.build_config.name }}
          path: ~/Paddle/Build/paddle_inference_c_install_dir/*

      - name: Upload paddle_inference_install_dir
        uses: actions/upload-artifact@v4
        with:
          name: cpp_${{ matrix.build_config.name }}
          path: ~/Paddle/Build/paddle_inference_install_dir/*
