name: paddle-windows-build-self-hosted
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/paddle-windows-build-self-hosted.yml'
  workflow_dispatch:

env:
  PADDLE_VERSION: "3.0.0"
  PADDLE_BRANCH: "v3.0.0"

jobs:
  build-all:
    runs-on: self-hosted
    strategy:
      max-parallel: 2
      matrix:
        build_config:
          # - name: openblas
          #   CMAKE_FLAGS: "-DWITH_AVX=ON -DWITH_MKL=OFF -DWITH_GPU=OFF"
          # - name: openblas_noavx
          #   CMAKE_FLAGS: "-DWITH_AVX=OFF -DWITH_MKL=OFF -DWITH_GPU=OFF"
          - name: mkldnn
            CMAKE_FLAGS: "-DWITH_AVX=ON -DWITH_MKL=ON -DWITH_GPU=OFF"
          - name: onednn
            CMAKE_FLAGS: "-DWITH_AVX=ON -DWITH_MKL=OFF -DWITH_GPU=OFF -DWITH_ONEDNN=ON"
          - name: openvino
            CMAKE_FLAGS: "-DWITH_AVX=ON -DWITH_MKL=OFF -DWITH_GPU=OFF -DWITH_OPENVINO=ON"
    steps:
      - name: Clean up
        run: |
          Get-ChildItem -Path .\ -Force -Recurse | Remove-Item -Force -Recurse -ErrorAction SilentlyContinue

      - name: Setup dependencies
        run: |
          pip3 install numpy protobuf wheel ninja

      - uses: ilammy/msvc-dev-cmd@v1
        with:
          toolset: '14.29'

      - name: Checkout Paddle repository
        uses: actions/checkout@v4
        with:
          repository: PaddlePaddle/Paddle
          ref: ${{ env.PADDLE_BRANCH }}
          path: ./Paddle
          fetch-depth: 1

      - name: Configure with CMake
        run: |
          mkdir .\Paddle\Build
          cd .\Paddle\Build
          cmake .. -GNinja `
            ${{ matrix.build_config.CMAKE_FLAGS }} `
            -DWITH_GPU=OFF `
            -DON_INFER=ON `
            -DWITH_PYTHON=OFF `
            -DWITH_ONNXRUNTIME=ON `
            -DWITH_UNITY_BUILD=ON

      - name: Build with Ninja
        run: |
          cd .\Paddle\Build
          ninja -j 10 all

      - name: Copy common* files
        run: |
          cp .\Paddle\Build\paddle_inference_install_dir\paddle\lib\common* .\Paddle\Build\paddle_inference_c_install_dir\paddle\lib
          ls .\Paddle\Build

      - name: Upload paddle_inference_c_install_dir
        uses: actions/upload-artifact@v4
        with:
          name: c_${{ matrix.build_config.name }}
          path: .\Paddle\Build\paddle_inference_c_install_dir\*

      - name: Upload paddle_inference_install_dir
        uses: actions/upload-artifact@v4
        with:
          name: cpp_${{ matrix.build_config.name }}
          path: .\Paddle\Build\paddle_inference_install_dir\*