name: Hello World Workflow

on:
  push:
    branches:
    - main

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    container:
      image: centos:7
    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
      - name: show dotnet version
        run: dotnet --info