name: Hello World Workflow

on:
  push:
    branches:
    - main

jobs:
  hello_world_job:
    runs-on: ubuntu-24.04
    steps:
      - name: info
        run: |
          echo "CPU 信息：" && lscpu && echo "内存信息：" && free -h
