name: Hello World Workflow

on:
  push:
    branches:
    - main

jobs:
  hello_world_job:
    runs-on: ubuntu-20.04
    container:
      image: centos:7
    steps:
      - name: checkout
        uses: actions/checkout@v3