name: Hello World Workflow

on:
  push:
    branches:
    - main

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    container:
      image: centos:7
    steps:
      - name: dotnet version
        run: |
          echo "Hello World!"
          dotnet --info