name: Hello World Workflow

on:
  push:
    branches:
    - main

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    container:
      image: centos:7
    steps:
      - name: setup dotnet
        run: |
          yum install epel-release -y
          rpm -Uvh https://packages.microsoft.com/config/rhel/7/packages-microsoft-prod.rpm
          yum update 
          yum search dotnet-sdk
          yum install dotnet-sdk-6.0

      - name: Check dotnet version
        run: dotnet --info