name: Hello World Workflow

on:
  push:
    branches:
    - main

jobs:
  hello_world_job:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        run: |
          echo "CPU 信息：" && lscpu | grep -E 'Model name|CPU MHz|Architecture' && echo "内存信息：" && free -h
