name: Hello World Workflow

on:
  push:
    branches:
    - main

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    container:
      image: centos:7
    steps:
      - name: setup dotnet
        run: |
          sudo rpm -Uvh https://packages.microsoft.com/config/rhel/7/packages-microsoft-prod.rpm
          sudo yum update 
          sudo yum install dotnet-sdk-6.0
          
      - name: Check dotnet version
        run: dotnet --info